export const locations = [
  { label: "Hà Nội", value: "hanoi", description: "Thủ đô Việt Nam (Capital of Vietnam)" },
  { label: "Hồ Chí Minh", value: "hcmc", description: "Thành phố Hồ Chí Minh (Ho Chi Minh City)" },
  { label: "An Giang", value: "angiang", description: "Tỉnh An Giang" },
  { label: "Bà Rịa - Vũng Tàu", value: "baria-vungtau", description: "Tỉnh Bà Rịa - Vũng Tàu" },
  { label: "Bắc Giang", value: "bacgiang", description: "Tỉnh Bắc Giang" },
  { label: "Bắc Kạn", value: "backan", description: "Tỉnh Bắc Kạn" },
  { label: "Bạc Liêu", value: "baclieu", description: "Tỉnh Bạc Liêu" },
  { label: "Bắc Ninh", value: "bacninh", description: "Tỉnh Bắc Ninh" },
  { label: "Bến Tre", value: "bentre", description: "Tỉnh Bến Tre" },
  { label: "Bình Định", value: "binhdinh", description: "Tỉnh Bình Định" },
  { label: "Bình Dương", value: "binhduong", description: "Tỉnh Bình Dương" },
  { label: "Bình Phước", value: "binhphuoc", description: "Tỉnh Bình Phước" },
  { label: "Bình Thuận", value: "binhthuan", description: "Tỉnh Bình Thuận" },
  { label: "Cà Mau", value: "camau", description: "Tỉnh Cà Mau" },
  { label: "Cần Thơ", value: "cantho", description: "Thành phố Cần Thơ" },
  { label: "Cao Bằng", value: "caobang", description: "Tỉnh Cao Bằng" },
  { label: "Đà Nẵng", value: "danang", description: "Thành phố Đà Nẵng" },
  { label: "Đắk Lắk", value: "daklak", description: "Tỉnh Đắk Lắk" },
  { label: "Đắk Nông", value: "daknong", description: "Tỉnh Đắk Nông" },
  { label: "Điện Biên", value: "dienBien", description: "Tỉnh Điện Biên" },
  { label: "Đồng Nai", value: "dongnai", description: "Tỉnh Đồng Nai" },
  { label: "Đồng Tháp", value: "dongthap", description: "Tỉnh Đồng Tháp" },
  { label: "Gia Lai", value: "gialai", description: "Tỉnh Gia Lai" },
  { label: "Hà Giang", value: "hagiang", description: "Tỉnh Hà Giang" },
  { label: "Hà Nam", value: "hanam", description: "Tỉnh Hà Nam" },
  { label: "Hà Tĩnh", value: "hatinh", description: "Tỉnh Hà Tĩnh" },
  { label: "Hải Dương", value: "haiduong", description: "Tỉnh Hải Dương" },
  { label: "Hải Phòng", value: "haiphong", description: "Thành phố Hải Phòng" },
  { label: "Hậu Giang", value: "haugiang", description: "Tỉnh Hậu Giang" },
  { label: "Hòa Bình", value: "hoabinh", description: "Tỉnh Hòa Bình" },
  { label: "Hưng Yên", value: "hungyen", description: "Tỉnh Hưng Yên" },
  { label: "Khánh Hòa", value: "khanhhoa", description: "Tỉnh Khánh Hòa" },
  { label: "Kiên Giang", value: "kiengiang", description: "Tỉnh Kiên Giang" },
  { label: "Kon Tum", value: "kontum", description: "Tỉnh Kon Tum" },
  { label: "Lai Châu", value: "laichau", description: "Tỉnh Lai Châu" },
  { label: "Lâm Đồng", value: "lamdong", description: "Tỉnh Lâm Đồng" },
  { label: "Lạng Sơn", value: "langson", description: "Tỉnh Lạng Sơn" },
  { label: "Lào Cai", value: "laocai", description: "Tỉnh Lào Cai" },
  { label: "Long An", value: "longan", description: "Tỉnh Long An" },
  { label: "Nam Định", value: "namdinh", description: "Tỉnh Nam Định" },
  { label: "Nghệ An", value: "nghean", description: "Tỉnh Nghệ An" },
  { label: "Ninh Bình", value: "ninhbinh", description: "Tỉnh Ninh Bình" },
  { label: "Ninh Thuận", value: "ninhthuan", description: "Tỉnh Ninh Thuận" },
  { label: "Phú Thọ", value: "phutho", description: "Tỉnh Phú Thọ" },
  { label: "Phú Yên", value: "phuyen", description: "Tỉnh Phú Yên" },
  { label: "Quảng Bình", value: "quangbinh", description: "Tỉnh Quảng Bình" },
  { label: "Quảng Nam", value: "quangnam", description: "Tỉnh Quảng Nam" },
  { label: "Quảng Ngãi", value: "quangngai", description: "Tỉnh Quảng Ngãi" },
  { label: "Quảng Ninh", value: "quangninh", description: "Tỉnh Quảng Ninh" },
  { label: "Quảng Trị", value: "quangtri", description: "Tỉnh Quảng Trị" },
  { label: "Sóc Trăng", value: "soctrang", description: "Tỉnh Sóc Trăng" },
  { label: "Sơn La", value: "sonla", description: "Tỉnh Sơn La" },
  { label: "Tây Ninh", value: "tayninh", description: "Tỉnh Tây Ninh" },
  { label: "Thái Bình", value: "thaibinh", description: "Tỉnh Thái Bình" },
  { label: "Thái Nguyên", value: "thainguyen", description: "Tỉnh Thái Nguyên" },
  { label: "Thanh Hóa", value: "thanhhoa", description: "Tỉnh Thanh Hóa" },
  { label: "Thừa Thiên Huế", value: "hue", description: "Tỉnh Thừa Thiên Huế" },
  { label: "Tiền Giang", value: "tiengiang", description: "Tỉnh Tiền Giang" },
  { label: "Trà Vinh", value: "travinh", description: "Tỉnh Trà Vinh" },
  { label: "Tuyên Quang", value: "tuyenquang", description: "Tỉnh Tuyên Quang" },
  { label: "Vĩnh Long", value: "vinhlong", description: "Tỉnh Vĩnh Long" },
  { label: "Vĩnh Phúc", value: "vinhphuc", description: "Tỉnh Vĩnh Phúc" },
  { label: "Yên Bái", value: "yenbai", description: "Tỉnh Yên Bái" }
];