import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./providers/providers";
import Header from "./components/layouts/header/Header";
import Footer from "./components/layouts/footer/Footer";
import OTPConfirmModal from "./components/ui/Modals/OTPmodal";
import ClientOnly from "./components/ClientOnly";
import { AuthProvider } from "./providers/authprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SeasonDecor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth !pr-0" suppressHydrationWarning>
      <body className="antialiased dark:bg-black">
        <AuthProvider>
          <ClientOnly>
            <AppProviders>
              <div className="flex min-h-screen flex-col">
                <Header />
                <OTPConfirmModal />
                <main className="flex-1">{children}</main>
                <Footer />
              </div>
            </AppProviders>
          </ClientOnly>
        </AuthProvider>
      </body>
    </html>
  );
}
