import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/providers";
import Header from "./components/layouts/header/Header";
import Footer from "./components/layouts/footer/Footer";
import { Toasterprovider } from "./providers/toasterprovider";
import ReduxProvider from "./providers/reduxprovider";
import AuthProvider from "./providers/authprovider"; // Import mới
import OTPConfirmModal from "./components/ui/Modals/OTPmodal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SeasonDecor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning>
      <body className="antialiased dark:bg-black">
        <ReduxProvider>
          <AuthProvider> {/* Bọc trong AuthProvider */}
            <Providers>
              <Toasterprovider />

              <div className="flex min-h-screen flex-col">
                <Header />
                <OTPConfirmModal />
                <main className="flex-1">{children}</main>
                <Footer />
              </div>
            </Providers>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
